### ISSUE TITLE
Add an `environment.yml` file

### ISSUE THREAD

**Issue by erikmannerfelt** [eliskasieglova/SvalbardSurges#5]
Right now, we have a pretty good view of the dependencies that are required for the code to run. To make it easy to install on new computers, it's nice with an "environment file". This file is an instruction on how to recreate this environment using conda/mamba. It's relatively easy to set up:

```yaml
name: SvalbardSurges
channels:
  - conda-forge
dependencies:
  - python >= 3.10
  - geopandas
  - xarray
  - netcdf4
  - matplotlib
  - rasterio
  - pip:
    - variete
```
Note that the `pyproj` hack that we made with pip is not present here. It could be added as a pip dependency, but the problem is (or at least should be) unique to your computer for some reason. Therefore it's best to not add this hack, but perhaps add that to the (not yet existing) `README.md`:
```markdown
## Installation
pyproj seems to sometimes not work properly from the conda-forge channel, and may need to be installed with pip instead.

conda remove -f pyproj
pip install pyproj

```
